### ISSUE TITLE
Unhandled exception 

### ISSUE THREAD

**Issue by ghost** [ipopov/starttls-mitm#2]
Hello,

I am getting the following error.

LISTENER ready on port 5222
CLIENT CONNECT from: ('10.2.10.237', 2187)
Unhandled exception in thread started by <function child at 0x8c6ccdc>
Traceback (most recent call last):
  File "mitm_listener.py", line 63, in child
    targetsock.connect((target,PORT))
  File "<string>", line 1, in connect
socket.error: [Errno 111] Connection refused

**Comment by ghost** [comment]
please ignore .. my bad
